---
kind: pipeline
name: constructor
steps:
  - name: landing-html
    image: mhart/alpine-node:10
    when:
      branch:
        - develop
    commands:
      - npm install -g npm
      - npm install
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host_name
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      script:
        - echo "Here we are"
        - docker stop landing-html
        - docker rm -f landing-html
        - docker run --restart always --name landing-html \
        - -e VIRTUAL_HOST=testpage.pechkin.space \
        - -e LETSENCRYPT_HOST=testpage.pechkin.space \
        - -e LETSENCRYPT_EMAIL=anatmozg@mail.ru \
        - -d landing-html
        - docker rmi $(docker images -f "dangling=true" -q)
    when:
      branch:
        - develop
---
kind: signature
hmac: 1d85d5e140edb6db0350e7596eb88535cb21583b44f7aab5fdcf6520a8b66f1b

...
