---
kind: pipeline
name: constructor
steps:
  - name: create-image
    image: mhart/alpine-node:10
    when:
      branch:
        - develop
    commands:
      - npm install -g npm
      - npm install
  - name: create-image-feature
    image: mhart/alpine-node:10
    when:
      branch:
        - feature/*
    commands:
      - npm install -g npm
      - npm install
  - name: docker-feature
    image: plugins/docker
    when:
      branch:
        - feature/*
    settings:
      repo: tolych/landing-html
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  - name: pull-and-run
    image: appleboy/drone-ssh
    settings:
      host: pechkin.space
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      script:
        - echo "Here we are"
        - docker rm -f landing-html
        - docker run --restart always --name landing-html --network=webproxy \
        - -e VIRTUAL_HOST=testpage.pechkin.space \
        - -e VIRTUAL_PORT=1337 \
        - -e LETSENCRYPT_HOST=testpage.pechkin.space \
        - -e LETSENCRYPT_EMAIL=anatmozg@mail.ru \
        - -d landing-html
        - docker image prune -f
    when:
      branch:
        - develop
---
kind: signature
hmac: ae36ec77c12ca347c9e5a598e059fa928cdf87e10fcb3b846226e53a99ae7473

...
