---
kind: pipeline
name: constructor
steps:
  - name: create-image
    image: mhart/alpine-node:10
    when:
      branch:
        - develop
    commands:
      - npm install -g npm
      - npm install
  - name: create-image-feature
    image: mhart/alpine-node:10
    when:
      branch:
        - feature/*
    commands:
      - npm install -g npm
      - npm install
  - name: docker
    image: plugins/docker
    when:
      branch:
        - develop
    settings:
      repo: tolych/landing-html-dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  - name: docker-feature
    image: plugins/docker
    when:
      branch:
        - feature/*
    settings:
      repo: tolych/landing-html-feature
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  - name: run-develop
    image: appleboy/drone-ssh
    settings:
      host: pechkin.space
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      script:
        - echo "Here we are"
        - docker rm -f landing-html
        - docker run --restart always --name landing-html --network=webproxy \
        - -e VIRTUAL_HOST=testpage.pechkin.space \
        - -e VIRTUAL_PORT=1337 \
        - -e LETSENCRYPT_HOST=testpage.pechkin.space \
        - -e LETSENCRYPT_EMAIL=anatmozg@mail.ru \
        - -d landing-html
        - docker image prune -f
    when:
      branch:
        - develop
  - name: run-feature
    image: appleboy/drone-ssh
    settings:
      host: pechkin.space
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port:
        from_secret: ssh_port
      script:
        - echo "Here we are"
        - docker pull tolych/landing-html-feature
        - docker rm -f landing-html-feature
        - docker run --restart always --name landing-html-feature --network=webproxy \
        - -e VIRTUAL_HOST=feature.pechkin.space \
        - -e VIRTUAL_PORT=1337 \
        - -e LETSENCRYPT_HOST=feature.pechkin.space \
        - -e LETSENCRYPT_EMAIL=anatmozg@mail.ru \
        - -d tolych/landing-html-feature
        - docker image prune -f
    when:
      branch:
        - feature/*
---
kind: signature
hmac: 2fee90255b73f8a7305cc7fdad498ab23c711e2c1543ca4ebe13347d51c848fe

...
