---
kind: pipeline
name: constructor
steps:
  - name: create-image
    image: mhart/alpine-node:10
    when:
      branch:
        - develop
        - master
        - feature/*
    commands:
      - npm install -g npm
      - npm install
  - name: docker
    image: plugins/docker
    when:
      branch:
        - master
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: tolych/landing-html
      tags: latest
  - name: docker-develop
    image: plugins/docker
    when:
      branch:
        - develop
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: tolych/landing-html-dev
      tags: latest
  - name: docker-feature
    image: plugins/docker
    when:
      branch:
        - feature/*
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: tolych/landing-html-feature
      tags: latest
  - name: run-master
    image: appleboy/drone-ssh
    settings:
      host: pechkin.space
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port:
        from_secret: ssh_port
      script:
        - echo "Here we are, let's go master"
        - docker pull tolych/landing-html
        - docker run --restart always --name landing-html --network=webproxy \
        - -e VIRTUAL_HOST=html.pechkin.space \
        - -e VIRTUAL_PORT=1337 \
        - -e LETSENCRYPT_HOST=html.pechkin.space \
        - -e LETSENCRYPT_EMAIL=anatmozg@mail.ru \
        - -d tolych/landing-html
        - docker image prune -f
    when:
      branch:
        - master
  - name: run-develop
    image: appleboy/drone-ssh
    settings:
      host: pechkin.space
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port:
        from_secret: ssh_port
      script:
        - echo "Here we are, let's go develop"
        - docker pull tolych/landing-html-dev
        - docker run --restart always --name landing-html-dev --network=webproxy \
        - -e VIRTUAL_HOST=dev-html.pechkin.space \
        - -e VIRTUAL_PORT=1337 \
        - -e LETSENCRYPT_HOST=dev-html.pechkin.space \
        - -e LETSENCRYPT_EMAIL=anatmozg@mail.ru \
        - -d tolych/landing-html-dev
        - docker image prune -f
    when:
      branch:
        - develop
  - name: run-feature
    image: appleboy/drone-ssh
    settings:
      host: pechkin.space
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port:
        from_secret: ssh_port
      script:
        - echo "Here we are, let's go feature"
        - docker pull tolych/landing-html-feature
        - docker rm -f landing-html-feature
        - docker run --restart always --name landing-html-feature --network=webproxy \
        - -e VIRTUAL_HOST=feature-html.pechkin.space \
        - -e VIRTUAL_PORT=1337 \
        - -e LETSENCRYPT_HOST=feature-html.pechkin.space \
        - -e LETSENCRYPT_EMAIL=anatmozg@mail.ru \
        - -d tolych/landing-html-feature
        - docker image prune -f
    when:
      branch:
        - feature/*
---
kind: signature
hmac: 0d03e0ea93005fb0269e44172c52614a64a7d4eaeaebe7b04739b0bd097953ba

...
