---
kind: pipeline
name: constructor
steps:
  - name: landing-html
    image: mhart/alpine-node:10
    when:
      branch:
        - develop
    commands:
      - npm install -g npm
      - npm install
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host: pechkin.space
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      script:
        - echo "Here we are"
        - docker rm -f landing-html
        - docker run --restart always --name landing-html --network=webproxy \
        - -e VIRTUAL_HOST=testpage.pechkin.space \
        - -e VIRTUAL_PORT=1337 \
        - -e LETSENCRYPT_HOST=testpage.pechkin.space \
        - -e LETSENCRYPT_EMAIL=anatmozg@mail.ru \
        - -d landing-html
        - docker image prune -f
    when:
      branch:
        - develop
---
kind: signature
hmac: c6c00ab4810fef86d39b6a9f448cd0317ea8203d328b01559abcb6792af822b8

...
